version: '2'

services:
  drupal:
    container_name: drupal
    image: custom-drupal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - drupal-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
